apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: yob-test-password
  namespace: yob-test2
spec:
  type: kv-v2
  mount: kv-v2
  path: yobtest3
  destination:
    name: yob-test-password
    create: true
  refreshAfter: 30s
  vaultAuthRef: approle-auth
