apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultsyncs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          description: VaultSync is the CRD schema for VaultSync operator
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema'
              type: string
            kind:
              description: 'Kind defines the resource'
              type: string
            spec:
              description: 'Spec defines the desired state of the resource'
              type: object
              properties:
                application:
                  description: 'Application name'
                  type: string
                vaultnamespace:
                  description: 'Vault namespace to create or sync with'
                  type: string
                token:
                  description: 'Authorization token to allow access to the vault namespace. 
                    Will be created during namespace creation or validated if namespace already exists'
                  type: string
            status:
              description: 'Status defines the observed state of the resource'
              type: object
              properties:
                conditions:
                  description: 'Observed state of the resource'
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        description: 'Last time the condition transitioned'
                        format: date-time
                        type: string
                      message:
                        description: 'Human readable message'
                        maxLength: 1024
                        type: string
                      observedGeneration:
                        description: 'Links condition to metadata.generation'
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: 'Reason for last transition'
                        maxLength: 1024
                        type: string
                      status:
                        description: 'Status of the condition'
                        enum:
                        - "True"
                        - "False"
                        - Unknown
                        type: string
                      type:
                        description: 'Type of the condition'
                        maxLength: 316
                        type: string
                    required:
                    - lastTransitionTime
                    - message
                    - reason
                    - status
                    - type
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    plural: vaultsyncs
    singular: vaultsync
    kind: VaultSync
    listKind: VaultSyncList
    shortNames:
    - vc
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
